[package]
name = "fido"
description = "Fido CLI"
version = "0.1.0"
edition = "2021"
authors = ["Bradley Reynolds <bradley.reynolds@darbia.dev>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/darbiadev/fido/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
clap = { version = "3.1.18", features = ["cargo"] }
clap_complete = "3.1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["json"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
business_central = { git = "https://github.com/darbiadev/business-central-rs" }
zendesk = { git = "https://github.com/darbiadev/zendesk-rs" }
figment = { version = "0.10.6", features = ["env", "toml"] }
dirs = "4.0.0"
futures = "0.3.21"
