name: "GitHub Pages - Rust doc"

on:
  push:
    branches:
      - main

jobs:
  docs:
    uses: darbiadev/.github/.github/workflows/github-pages-rust-doc.yaml@c194ec59628447c17718ee155e52060ef92dc406
