name: "Rust CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    uses: darbiadev/.github/.github/workflows/rust-lint.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0

  clippy:
    needs: lint
    uses: darbiadev/.github/.github/workflows/rust-clippy.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0

  test:
    needs: clippy
    strategy:
      matrix:
        triple:
          - { os: "ubuntu-latest", target: "x86_64-unknown-linux-gnu" }

    uses: darbiadev/.github/.github/workflows/rust-test.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0
    with:
      os: ${{ matrix.triple.os }}
      target: ${{ matrix.triple.target }}

  docs:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: darbiadev/.github/.github/workflows/github-pages-rust-doc.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Cache Rust and project dependencies"
        id: cache
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ hashFiles('Cargo.lock') }}

      - name: "Install grcov"
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install grcov

      - name: "Run tests"
        run: cargo test --no-fail-fast
        env:
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "selene-%p-%m.profraw"

      - name: "Generate coverage data"
        run: |
          grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info

      - name: "Upload coverage reports to Codecov"
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
